# Generated by Django 5.2.1 on 2025-05-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_barangay_address_city_address_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('SEPARATED', 'Separated'), ('COHABITATION', 'Cohabitation (live-in)'), ('MARRIED', 'Married'), ('WIDOW/ER', 'Widow/er')])),
                ('landline', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
    ]
