# Generated by Django 5.2.1 on 2025-05-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_educationalattainment_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_firtname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_middlename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=255)),
                ('specify', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='education_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.educationalattainment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='family_details_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.familydetail'),
        ),
    ]
