# Generated by Django 5.2.1 on 2025-05-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_familydetail_occupation_applicant_education_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF-EMPLOYED', 'Self-employed')], max_length=30)),
                ('emp_category', models.CharField(blank=True, choices=[('GOVERMENT', 'Government'), ('PRIVATE', 'Private')], max_length=30, null=True)),
                ('emp_type', models.CharField(blank=True, choices=[('CASUAL', 'Government'), ('EMERGENCY', 'Emergency'), ('REGULAR', 'Permanent/Regular'), ('SEASONAL', 'Seasonal')], max_length=30, null=True)),
                ('affiliated_org', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.occupation')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='emp_info_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employmentinfo'),
        ),
    ]
