# Generated by Django 5.2.1 on 2025-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employmentinfo_applicant_emp_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='specify',
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='specify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
