# Generated by Django 5.2.1 on 2025-05-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_occupation_specify_employmentinfo_specify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
