# Generated by Django 5.2.1 on 2025-05-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='landline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employmentinfo',
            name='emp_type',
            field=models.CharField(blank=True, choices=[('CASUAL', 'Casual'), ('EMERGENCY', 'Emergency'), ('REGULAR', 'Permanent/Regular'), ('SEASONAL', 'Seasonal')], max_length=30, null=True),
        ),
    ]
