# Generated by Django 5.2.1 on 2025-05-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_applicant_email_alter_applicant_landline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='family_details_id',
            new_name='family_detail_id',
        ),
    ]
