# Generated by Django 5.2.1 on 2025-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_family_details_id_applicant_family_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinfo',
            name='specify',
        ),
        migrations.AddField(
            model_name='occupation',
            name='specify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
