# Generated by Django 5.2.1 on 2025-05-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_employmentinfo_specify_occupation_specify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='specify',
        ),
    ]
