# Generated by Django 5.2.1 on 2025-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_occupation_specify'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinfo',
            name='other_occupation_specify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
