# Generated by Django 5.2.1 on 2025-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employmentinfo_other_occupation_specify'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gsis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pagibig_no', models.CharField(blank=True, max_length=50, null=True)),
                ('psn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('philhealth_no', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
