# Generated by Django 5.2.1 on 2025-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_identifierinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='education_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='family_detail_id',
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='barangay',
            new_name='barangay_id',
        ),
        migrations.AddField(
            model_name='applicant',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.CharField(blank=True, choices=[(1, 'None'), (2, 'Kindergarten'), (3, 'Elementary'), (4, 'Junior High School'), (5, 'Senior High School'), (6, 'College High School'), (7, 'Vocational High School'), (8, 'Post Graduate')], null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='family_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='registration_no',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='EducationalAttainment',
        ),
        migrations.DeleteModel(
            name='FamilyDetail',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
