# Generated by Django 5.2.1 on 2025-05-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_application_processing_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
    ]
