# Generated by Django 5.2.1 on 2025-05-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_applicant_id_application_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='emp_info_id',
            new_name='emp_info',
        ),
    ]
