# Generated by Django 5.2.1 on 2025-05-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_address_barangay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='address',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='employmentinfo',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='employmentinfo',
            name='deleted_by_cascade',
        ),
    ]
