# Generated by Django 5.2.1 on 2025-05-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_address_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='identifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='barangay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.barangay'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='emp_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employmentinfo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicantDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disabilityorigin')),
            ],
        ),
    ]
