# Generated by Django 5.2.1 on 2025-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_disabilitycategory_disabilityorigin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentifierInfo',
        ),
    ]
