# Generated by Django 5.2.1 on 2025-05-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_delete_identifierinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdisability',
            name='specific_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.specificdisability'),
        ),
    ]
