# Generated by Django 5.2.1 on 2025-05-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_applicantdisability_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentinfo',
            name='emp_category',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PWDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_died', models.DateField(blank=True, null=True)),
                ('pwd_card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
        ),
    ]
