# Generated by Django 5.2.1 on 2025-05-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_application_processing_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificdisability',
            name='disability_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disabilitycategory'),
        ),
    ]
