# Generated by Django 5.2.1 on 2025-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_specificdisability_disability_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificdisability',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
