# Generated by Django 5.2.1 on 2025-05-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
