# Generated by Django 5.2.1 on 2025-05-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwdprofile',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pwdprofiles', to='api.application'),
        ),
    ]
